### ISSUE TITLE
Version info via the -h flag please and error message when executing 1.00 release 

### ISSUE THREAD

**Issue by tkremer2005** [davelarsen58/pmemtool#10]
Hi Dave,

would it be possible to show the pmemtool version as part of the -h or as a parameter please? 

Also since we updated to version 1.00 I get this error when running pmt:
xxxxxxxxxx:/usr/share/pmemtool-main # pmt
Traceback (most recent call last):
  File "./pmt", line 239, in <module>
    main(sys.argv[1:])
  File "./pmt", line 142, in main
    i.dimms = i.parse_dimm()
  File "/usr/share/pmemtool-main/ipmctl.py", line 233, in parse_dimm
    if white_list[root[dimm][dimm_attr].tag] == 1:
KeyError: 'FWActiveAPIVersion'

**Comment by davelarsen58** [comment]
Integrated into Release 1.01.0

**Comment by davelarsen58** [comment]
Integrated into Release 1.01.0
